version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.7.1
    - 7.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
  - dependency-name: np
    versions:
    - 7.4.0
  - dependency-name: typescript
    versions:
    - 4.1.4
